### ISSUE TITLE
Migrate autofs module to Vox Pupuli

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet-autofs#1]
Tracking progress for migration to VoxPupuli

- [x] Ask one of the Administrators to add you to the modules/admin team.
- [x] At that point you can transfer your own repository
- [x] If migrating a module from puppetlabs, re-enable github issues.
- [x] Verify that all webhooks except travis are disabled.
- [x] Update the README.md with a description of the deprecation and a link to the new module location.
- [x] Release a 999.999.999 version of the original module to the forge, so users and tools knows to stop using it.
- [x] Release a copy of your module to the ‘puppet’ forge account.
- [x] Add the module to our modulesync setup
- [x] Add the module to our plumbing repository(handles travis secrets)
- [x] Ask one of the Admins to add the module to the collaborators Team on github.
- [x] Resubmit to Puppet JIRA for review and move "Approved" badge to new namespace

**Comment by bastelfreak** [comment]
I did a few things and updated the checklist

**Comment by dhollinger** [comment]
Add two additional tasks involving tests and migrating the "Approved" badge

**Comment by dhollinger** [comment]
Deployed to the puppet namespace on the forge.

Dhollinger autofs released with 999.999.999 and link to new page.

**Comment by dhollinger** [comment]
Submitted https://tickets.puppetlabs.com/browse/MODULES-4262 to get the Approved banner migrated to the new location
