### ISSUE TITLE
Documentation uses wrong name for autofs::map::mapfile

### ISSUE THREAD

**Issue by jcbollinger** [voxpupuli/puppet-autofs#101]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 2.1
- Distribution: RedHat 7.4
- Module version: 4.3.0

## How to reproduce (e.g Puppet code you use)
Pursuant to the current examples and defined-type detail documentation in README.md, I declared
```
autofs::map { 'test':
  map => '/etc/test.auto',
  mapcontents => ['test defaults test.my.com:/test']
}
```
## What are you seeing
Catalog compilation fails with two errors:
```
Evaluation Error: Error while evaluating a Resource Statement, Autofs::Map[test]:
  has no parameter named 'map'
  parameter 'mapfile' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)*$/]] value, got String
```

## What behaviour did you expect instead
Catalog compilation should succeed, and the resulting catalog should manage an indirect automount map in file `/etc/test.auto`.

## Output log
The failure can be made to occur in RSpec tests, producing this output:

```
failed: rspec: ./spec/classes/test_spec.rb:8: error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Autofs::Map[test]:
  has no parameter named 'map'
  parameter 'mapfile' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)*$/]] value, got String (file: /home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/sb/spec/fixtures/modules/sb/manifests/test.pp, line: 10) on node svlpsbpuppet01.stjude.org
  sb::test on redhat-7-x86_64 should compile into a catalogue without dependency cycles
  Failure/Error:
        let(:facts) { os_facts }
  
        it { is_expected.to compile }
      end
    end
```

## Any additional information you'd like to impart
Notwithstanding the module documentation to the contrary (defined type detail documentation and multiple examples), the actual name of the autofs::map parameter in question is 'mapfile', not 'map'.  Changing the parameter name accordingly resolves the catalog compilation error.

**Comment by ekohl** [comment]
Could you come up with a PR to fix this?

**Comment by jcbollinger** [comment]
I am working on a PR.  It looks like it may make somewhat broader documentation changes than issue #101 describes; if you would like additional issues to be filed describing the reason for those additional edits then just let me know.
