### ISSUE TITLE
Feature: Add support for Darwin

### ISSUE THREAD

**Issue by helge000** [voxpupuli/puppet-autofs#127]
Support for Darwin is quite simple to add IMHO.

**Comment by dhollinger** [comment]
We can merge #128, but it is important to note that we as a community are not equipped to officially support Darwin/MacOS from a troubleshooting standpoint

**Comment by helge000** [comment]
I just moved the line `Mac OS X` in README.md. There, it already states:

> Self Support - should work, support not provided by developer

I think this covers your concern, @dhollinger ?

**Comment by dhollinger** [comment]
closing as stale

**Comment by helge000** [comment]
@dhollinger, can you offer at least some reason for closing this PR?
I was waiting for a reply from you for eight months now, after all.

**Comment by Dan33l** [comment]
It was asked to remove MacOSX from the supported OSes in the PR. And it looks it was not done.
 As already said by @dhollinger : 
 * we can not run tests MasOSX in the CI
 * as a community are not equipped to officially support Darwin/MacOS.
