### ISSUE TITLE
Merge Unique

### ISSUE THREAD

**Issue by scarroyo** [voxpupuli/puppet-autofs#167]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by scarroyo** [comment]
Greetings,
 
I’ll preface this with the fact that I’m new to Puppet and our team at Los Alamos National Labs. I took on this task in hopes of learning more about Puppet. I apologize for not being more accurate in describing our issue.
 
We are using your autofs module, and could use advice or a perhaps request an enhancement. We have use cases where a ‘mount’ may have different ‘options’. Here’s where it gets fuzzy for me. The preference would be to have the ‘options’ merge unique when using the same ‘mount’.  When we define different options for the same mount, the puppet run errors.
 
I believe we want to define these differences in mount options at the highest Hiera data level and have them merge uniquely.
 
We attempted the following to force a unique merge unsuccessfully:
 
If I’m reading the documentation for “Set the merge behavior for a lookup” correctly, then the merge type of a module can be overridden in the hiera data common.yaml file. 
 
From this article: https://puppet.com/docs/puppet/7.4/hiera_merging.html#defining-merge-behavior-with-lookup_options  The merge behavior can be overridden 
 
# <ENVIRONMENT>/data/common.yaml
lookup_options:
  autofs::options:     # Name of key
    merge: unique      # change the default Merge behavior
 
 
Thank you,
Steven C. Arroyo

**Comment by kenyon** [comment]
There is no such parameter as `autofs::options`, so that `lookup_options` is doing nothing.

If you're trying to set default `options` for the `autofs::mapping` or `autofs::mount` defined resource types, you can do that in your puppet code or in hiera, but exactly how to do that depends on how you're creating these resources.
