### ISSUE TITLE
Add Support for RHEL 8

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-autofs#168]
It currently doesn't work but isn't listed as being supported either.  Please add support for RHEL 8.

**Comment by bschonec** [comment]
I'm using the module on RHEL8.  What issues are you seeing?

**Comment by rychannel** [comment]
I need to check and see, its been a long time since I tried using it on RHEL 8

**Comment by rychannel** [comment]
It appears to work now.  Probably need to get the docs updated to say the autofs modules with with RHEL 8 and Puppet 7

**Comment by kenyon** [comment]
Done in v7.0.0: https://github.com/voxpupuli/puppet-autofs/commit/ecd69e1f23384e4b17a516ac2948353cbcc5d569
