### ISSUE TITLE
Default auto.master

### ISSUE THREAD

**Issue by benkevan** [voxpupuli/puppet-autofs#18]
The default /etc/auto.master differs between several supported OSs. Therefore the users experience is different without an option to make the config alike across all. 

By default it'd be nice to have the following: 
/misc   /etc/auto.misc
/net    -hosts
+dir:/etc/auto.master.d
+auto.master

Maybe the capability is already there. I haven't looked at the code yet, just reviewed README

**Comment by dhollinger** [comment]
The default auto.master files are not included. this is primarily because mist use cases I've seen require a wholesale replacement of the default auto.master.

We could include a parameter that will use a different template that contains the default settings if necessary.

**Comment by benkevan** [comment]
That's be best because by default on some systems /etc/master.d isn't
sourced either (Suse for example).

Control of just the 3 optional parameters which are within default
auto.master would provide great control of what the module should achieve
across all systems and ensure the behavior is alike across all systems.

**Comment by dhollinger** [comment]
Are you saying that the version of autofs on Suse doesn't allow for sourcing of a master.d directory or that it's simply not the default?  (NOTE: This module does not source any /etc/auto.master.d by default, that has to be set).

I'm trying to make sure I understand before going through a lot of work to add some defaults. The goal with this module is to make configuring autofs as simple and universal across OSes as possible. Currently, anything applied by this module will replace all defaults. 

If autofs functionality isn't changed between OSes, then the current module defaults won't matter as autofs will know what to do.

As for those default settings, I would like more information as to why those need to be persisted before putting what could potentially be a lot of work for minimal gains. Why not just add those to your profile/hieradata if you need them to persist?

Any other thoughts?

**Comment by benkevan** [comment]
In SLES the directive to include auto.master.d isn't enabled by default
within auto.master.. neither are the directives for /net or /misc.

Therefor anything created within auto.master.d won't be externally sourced.
Nor would someone the behaviors across systems be the same.

I found this by trying to do a net install from /net which failed on SUSE
because the default /net rule wasn't in place.

**Comment by dhollinger** [comment]
Ok, in that case, as long as you don't specify `use_dir => true` or `use_dir: true` in the code or hieradata respectively, it won't even try to source the auto.master.d directory. Unless I'm missing something. 

We could add some logic to the defined type to force use_dir to `false` when SLES or SUSE are being used, but even that may be a little overboard.

**Comment by dhollinger** [comment]
@benkevan Did my last comment make sense or does it not solve the issue?

**Comment by benkevan** [comment]
I'll give it a whirl. That does make some sense, but overall the default
behavior is much different because /net, /misc and the master.d aren't
sourced.

It'd be nice to have the same auto.master across all systems. So behavior
is always alike.

**Comment by mterzo** [comment]
I'm trying to do something similar:

I'm using this hiera content:

```
classes:
  - autofs

autofs::mounts:
  net:
    mount: /net
    order: 1
    mapfile: /etc/auto.net
    options: -hosts
    use_dir: false
```

I tried leaving out the mapfile, but now that type has an issue when it's left blank.

```
parameter 'mapfile' expects a match for Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)+$/]], got '' at /etc/puppetlabs/code/environments/production/modules/autofs/manifests/init.pp:81
```


You put code to handle that originally:

```
  if $mapfile != '' {
    $contents = "${mount} ${mapfile} ${options}\n"
  } else {
    $contents = "${mount} ${options}\n"
  }
```
But this code will never get executed.

**Comment by clevelas** [comment]
I am needing the ability to add +auto.master to my auto_master.  The use case if we get most of our automounts from LDAP.  But for some machines, we have a need to specify additional custom mounts.

**Comment by dhollinger** [comment]
@clevelas With the way the code is setup, you can use node definitions or hieradata to dynamically set those per-machine configurations.

**Comment by dhollinger** [comment]
Closing due to age and I believe this was addressed
