### ISSUE TITLE
`mount` should not default to an empty array.

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-autofs#5]
https://github.com/voxpupuli/puppet-autofs/blob/f43a0f4bbdf34e1bbca3cf4288ff82ad383701a4/manifests/mounts.pp#L25 looks funky.
```puppet
$mount = hiera_hash('autofs::mounts', [])
```
`$mount` is passed to `create_resources` which takes a hash as its second argument, not an array.
I think the correct change isn't
```puppet
$mount = hiera_hash('autofs::mounts', {})
```
but perhaps
```puppet
$mount = hiera_hash('autofs::mounts', $::autofs::mounts)
```
In this way, the module would work for users who have passed a mounts hash to the base class explicitly as well as those using hiera.

There's also every chance I've just misread the code and this isn't a bug/issue at all! :)

**Comment by alexjfisher** [comment]
https://www.devco.net/archives/2016/03/13/the-puppet-4-lookup-function.php might also be worth a look at.  I've not yet personally used it, but I *think* it's now possible to do automatic parameter lookups of hash parameters from hiera *with* merging.

**Comment by dhollinger** [comment]
The code was originally designed only with hieradata in mind with the assumption that if a user wasn't using hieradata, they'd directly call the defined type.

In fact, I "stole" the idea from Gareth's Docker module's [images.pp](https://github.com/garethr/garethr-docker/blob/master/manifests/images.pp).

The use of hiera_hash was proposed in a PR back in October to account for repeating keys and native merging. After reviewing it, I merged it. That said, my understanding of hiera_hash is limited as I haven't had to use it yet, nor do I have a lot of experience with the lookup function yet
