### ISSUE TITLE
No option to remove an already defined autofs::mount

### ISSUE THREAD

**Issue by danyel2014** [voxpupuli/puppet-autofs#91]
Dear developers, 

today I just wanted to remove  an existing autofs::mount, but, there is no _ensure => absent_ option available. The only workaround I found was to set mapcontents => [], but this doesn't remove the entry in auto.master and also the mapfile is not removed. 

Would be possible to extend the module having in mind also the removal for already defined autofs::mount entries  ?

Thank you
Dan

**Comment by dhollinger** [comment]
I'll take a look at this requeset this week.

**Comment by dhollinger** [comment]
This is definitely a bug as it was intended to be able to remove mounts and maps as well

**Comment by dhollinger** [comment]
@danyel2014 added enhancements. See #95 for the changes.
