### ISSUE TITLE
Allow the special map name  "-hosts" in Autofs::Mapentry

### ISSUE THREAD

**Issue by heinerbillich** [voxpupuli/puppet-autofs#93]
I want to use the special  `-hosts` map in autofs. Something like

`/net   -hosts`

in auto.master. The puppet code to get this would be

```
  autofs::mount{'auto.NET':
    mount          => '/net',
    mapfile_manage => false,
    mapfile        => '-hosts',
  }
```

Currently the type Autofs::Mapentry doesn't allow `-hosts`, a simple addition to the regexp could fix this:

```
# type Autofs::Mapentry = Pattern[/^[a-z]+:\/([^\/\0]+(\/)?)+$/]
type Autofs::Mapentry = Pattern[/^[a-z]+:\/([^\/\0]+(\/)?)+$|^-hosts$/]
```

-hosts is the only such special map, hence just adding the full string and no pattern to the regexp seems o.k..

Does this fit into the module and is the  way to implement it o.k.? I'm not sure whether I can do all that's required to submit a pull request, I'm no developer, but I can do a start.

cheers,
Heiner Billich

**Comment by dhollinger** [comment]
@heinerbillich PR #94 contains the code for this enhancement
