### ISSUE TITLE
Add AIX support

### ISSUE THREAD

**Issue by TJM** [voxpupuli/puppet-autofs#96]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.4
- Ruby: AIO
- Distribution: AIX
- Module version: 4.2.0

I would like to add AIX support. As part of this, we will add module level hieradata.

**Comment by bastelfreak** [comment]
Hi @TJM. Thanks for the info. Patches are always welcome. Just open a PR for this and we will review & merge it.

**Comment by dhollinger** [comment]
This was merged in #97
